mission_manager:
  ros__parameters:

    # =====================================================
    # Topic
    # =====================================================

    # 고정 웹캠에서 계산한 자동차 map 위치
    target_position_topic: "/target/map_position"

    # AMR OAK-D 자동차 감지
    amr_detection_topic: "/amr/detections"

    # approach 노드 인터페이스
    approach_target_topic: "/approach/target_point"
    approach_cancel_topic: "/approach/cancel"
    approach_status_topic: "/approach/status"

    # TurtleBot4 속도 명령
    cmd_vel_topic: "/robot2/cmd_vel"

    # 좌표계
    map_frame: "map"

    # =====================================================
    # Following
    # =====================================================

    # AMR 카메라 영상 가로 크기
    image_width: 640

    # 추종할 때 자동차와 유지할 목표 거리 [m]
    target_distance: 0.3

    # 이 거리보다 가까우면 전진하지 않음 [m]
    min_distance: 0.5

    # 거리 오차 → 직진 속도 gain
    linear_gain: 0.5

    # 이미지 중심 오차 → 회전 속도 gain
    angular_gain: 1.0

    # 최대 속도
    max_linear_speed: 0.31
    max_angular_speed: 1.0

    # 마지막 자동차 감지를 유효하게 보는 시간 [s]
    detection_timeout: 0.5

    # HANDOVER → FOLLOWING 전환에 필요한 연속 감지 횟수
    handover_detection_count: 3


approach:
  ros__parameters:

    # =====================================================
    # Nav2
    # =====================================================

    nav_action: "/robot2/navigate_to_pose"
    pose_topic: "/robot2/amcl_pose"

    # mission_manager 인터페이스
    target_topic: "/approach/target_point"
    cancel_topic: "/approach/cancel"
    status_topic: "/approach/status"

    map_frame: "map"

    # =====================================================
    # 자동차를 보기 좋은 AMR 위치
    # =====================================================

    # car 위치 기준 AMR goal offset [m]
    #
    # 테스트:
    # car ≈ (-0.0355, 1.025)
    # AMR  ≈ (0.64, 1.84)
    #
    view_offset_x: 0.6755
    view_offset_y: 0.8150

    # 이동 중 자동차 위치가 이 거리 이상 바뀌었을 때만
    # 새로운 Nav2 goal로 교체
    retarget_threshold: 0.3